name: edunest_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.1.0
  sliding_up_panel: ^2.0.0+1
  uuid: ^4.5.1
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.4
  firebase_storage_web: ^3.6.4
  js: ^0.6.7
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  file_picker: ^8.0.7
  url_launcher: ^6.1.11
  intl: ^0.17.0
  http: ^1.1.2
  dio: ^5.4.0
  path_provider: ^2.1.2
  flutter_pdfview: ^1.3.2
  image_picker: ^1.0.7
  fl_chart: ^0.66.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_polyline_points: ^2.0.0
  flutter_svg: ^2.0.9
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_local_notifications: ^19.2.1
  google_maps_flutter: ^2.5.3
  permission_handler: ^11.3.0
  excel: ^2.1.0
  timeago: ^3.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


